# Generated by Django 4.0.3 on 2023-10-04 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_description_alter_book_genre'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
